org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

project.libs=26.2-SNAPSHOT
project.platforms=Common, Fabric, NeoForge
project.plugins=1.1-SNAPSHOT

mod.authors=Fuzs
mod.description=Heads up! Every mob, every head, all in one, proudly displayed.
mod.group=fuzs.alltheheads
mod.id=alltheheads
mod.license=MPL-2.0
mod.name=All The Heads
mod.version=26.2.1

dependencies.fabric.fabricapi=required
dependencies.fabric.forgeconfigapiport=required
dependencies.fabric.puzzleslib=required
dependencies.neoforge.puzzleslib=required

distributions.curseforge.id=1369265
distributions.curseforge.slug=all-the-heads
distributions.github.slug=all-the-heads
distributions.modrinth.id=Ax17wp3L
distributions.modrinth.slug=all-the-heads

environments.client=required
environments.server=required
